FROM golang:1.18
ENV TZ Asia/Tokyo
ENV GOBIN=/go/bin
WORKDIR /go/src/app
RUN go install github.com/x-motemen/gore/cmd/gore@latest && \
    go install github.com/go-delve/delve/cmd/dlv@master && \
    cp ${GOBIN}/dlv ${GOBIN}/dlv-dap && \
    go install golang.org/x/tools/gopls@latest && \
    go install golang.org/x/tools/cmd/goimports@latest && \
    go install github.com/ramya-rao-a/go-outline@latest && \
    go install github.com/stamblerre/gocode@latest && \
    go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest && \
    go install github.com/rogpeppe/godef@latest && \
    go install honnef.co/go/tools/cmd/staticcheck@latest && \
    # モックの定義を自動生成する
    go install github.com/vektra/mockery/v2@latest && \
    # 単体テストをいい感じに生成してくれるツール
    go install github.com/cweill/gotests/gotests@latest && \
    apt-get update && \
    apt-get install -y --no-install-recommends peco && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
